CC=gcc
CFLAGS= -Wall -Werror -Wextra -pedantic 

0-hreadelf:
	$(CC) $(CFLAGS) *.c -o 0-hreadelf

1-hreadelf:
	$(CC) $(CFLAGS) task1/1-hreadelf.c -o 1-hreadelf

2-hreadelf:
	$(CC) $(CFLAGS) task2/2-hreadelf.c -o 2-hreadelf

100-hreadelf:
	$(CC) $(CFLAGS) task3/100-hreadelf.c -o 100-hreadelf
